name: miapp
description: "A new Flutter project."

publish_to: 'none' # Evita publicar el paquete en pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'  # Ajustado a una versión estable

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.8
  go_router: ^13.2.0
  logger: ^2.0.2
  dio: ^5.3.2
  intl: ^0.18.0
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  sqflite: ^2.4.2
  path: ^1.8.3  # 🔹 Agrega esta línea
  http: ^0.13.6  # Asegúrate de que esta línea esté presente
  animated_text_kit: ^4.2.2  # Asegúrate de usar la última versión
  font_awesome_flutter: ^10.7.0
  flutter_typeahead: ^4.3.7  # Asegúrate de agregar esta línea
  flutter_keyboard_visibility: ^5.4.1
  permission_handler: ^11.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # 👈 Asegúrate de que esto esté aquí

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png  # 👈 Asegúrate de que este ícono esté registrado
    - assets/logo.png
